spring:
  profiles:
    active: local
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 100MB
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/photomap
    username: jmlee
    password: 1234
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: false
---
app:
  upload:
    dir: ${user.home}/Desktop/pics/